// LaTeX Generator for Contracts with professional formatting matching docs/format.tex
import jsPDF from 'jspdf';

export function generateLatex(content: string, contractType: string = 'contract'): string {
  // Escape special LaTeX characters
  const escapeLatex = (text: string): string => {
    return text
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/\$/g, '\\$')
      .replace(/%/g, '\\%')
      .replace(/&/g, '\\&')
      .replace(/_/g, '\\_')
      .replace(/#/g, '\\#')
      .replace(/~/g, '\\textasciitilde{}')
      .replace(/\^/g, '\\textasciicircum{}');
  };

  // Parse markdown content to LaTeX
  const parseMarkdownToLatex = (mdContent: string): string => {
    const lines = mdContent.split('\n');
    let latexBody = '';
    let inList = false;

    lines.forEach((line) => {
      const trimmed = line.trim();

      // Skip empty lines but add spacing
      if (trimmed === '') {
        if (inList) {
          latexBody += '\\end{itemize}\n';
          inList = false;
        }
        latexBody += '\n\\vspace{0.3cm}\n';
        return;
      }

      // Horizontal rule
      if (trimmed === '---') {
        if (inList) {
          latexBody += '\\end{itemize}\n';
          inList = false;
        }
        latexBody += '\\vspace{0.3cm}\n\\noindent\\rule{\\textwidth}{0.5pt}\n\\vspace{0.3cm}\n';
        return;
      }

      // Headers
      if (trimmed.startsWith('# ')) {
        if (inList) {
          latexBody += '\\end{itemize}\n';
          inList = false;
        }
        const text = escapeLatex(trimmed.substring(2));
        latexBody += `\n\\begin{center}\n{\\Large\\bfseries ${text}}\n\\end{center}\n\\vspace{0.4cm}\n`;
        return;
      }

      if (trimmed.startsWith('## ')) {
        if (inList) {
          latexBody += '\\end{itemize}\n';
          inList = false;
        }
        const text = escapeLatex(trimmed.substring(3));
        latexBody += `\n\\textbf{${text}}\n\\vspace{0.2cm}\n`;
        return;
      }

      if (trimmed.startsWith('### ')) {
        if (inList) {
          latexBody += '\\end{itemize}\n';
          inList = false;
        }
        const text = escapeLatex(trimmed.substring(4));
        latexBody += `\n\\textit{\\textbf{${text}}}\n\\vspace{0.15cm}\n`;
        return;
      }

      // List items
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        if (!inList) {
          latexBody += '\\begin{itemize}[leftmargin=1.2em]\n';
          inList = true;
        }
        const text = processInlineFormatting(escapeLatex(trimmed.substring(2)));
        latexBody += `  \\item ${text}\n`;
        return;
      }

      // Close list if we're in one
      if (inList && !trimmed.startsWith('- ') && !trimmed.startsWith('* ')) {
        latexBody += '\\end{itemize}\n\\vspace{0.2cm}\n';
        inList = false;
      }

      // Regular text with inline formatting
      const processedText = processInlineFormatting(escapeLatex(trimmed));
      latexBody += `${processedText}\n\n`;
    });

    // Close any open list
    if (inList) {
      latexBody += '\\end{itemize}\n';
    }

    return latexBody;
  };

  // Process inline formatting (bold, italic, etc.)
  const processInlineFormatting = (text: string): string => {
    // Bold text **text**
    text = text.replace(/\*\*(.+?)\*\*/g, '\\textbf{$1}');
    // Italic text *text* (but not after escaping)
    text = text.replace(/(?<![\\*])\*([^*]+?)\*/g, '\\textit{$1}');
    return text;
  };

  const latexBody = parseMarkdownToLatex(content);

  const contractTypeTitle = contractType.charAt(0).toUpperCase() + contractType.slice(1);

  // Generate complete LaTeX document matching format.tex style
  return `% eChukti Contract Document
% Generated by eChukti Platform
\\documentclass[12pt,a4paper]{article}

\\usepackage[margin=1in]{geometry}
\\usepackage{setspace}
\\usepackage{parskip}
\\usepackage{enumitem}
\\usepackage{array}
\\usepackage{fancyhdr}
\\usepackage{hyperref}

\\setstretch{1.15}

\\pagestyle{fancy}
\\fancyhf{}
\\lhead{\\textbf{eChukti} \\;|\\; ${contractTypeTitle} Contract}
\\rhead{\\thepage}
\\renewcommand{\\headrulewidth}{0.4pt}
\\cfoot{\\small Generated by eChukti Digital Platform}

\\begin{document}

${latexBody}

\\vspace{1.5cm}

\\noindent\\rule{\\textwidth}{0.5pt}

\\vspace{0.3cm}
\\begin{center}
\\small\\textit{This document was digitally generated by eChukti Platform.}\\\\
\\small\\textit{For verification, visit: https://echukti.com}
\\end{center}

\\end{document}`;
}

export function downloadLatexFile(content: string, filename: string = 'contract.tex') {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Generate high-quality PDF directly from markdown content matching format.tex exactly
export async function compileLatexToPdf(markdownContent: string, filename: string = 'contract.pdf'): Promise<void> {
  try {
    // Use markdown content directly
    
    // Generate high-quality PDF with format.tex styling
    // format.tex uses: 12pt font, a4paper, 1in margins, 1.15 line spacing
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
      compress: true
    });
    
    // A4 dimensions: 210mm x 297mm
    const pageWidth = 210;
    const pageHeight = 297;
    const margin = 25.4; // 1 inch margins (format.tex: \usepackage[margin=1in]{geometry})
    const maxLineWidth = pageWidth - (margin * 2);
    
    // format.tex uses \setstretch{1.15} - 1.15 line spacing
    // Base font 12pt in LaTeX ≈ 10pt in jsPDF (PDF points)
    const baseFontSize = 10; // Regular text
    const baseLineHeight = baseFontSize * 1.15 * 0.3527; // Convert to mm with 1.15 spacing
    
    let yPosition = margin;
    
    // Add header to first page (and will be added to subsequent pages)
    addLatexHeader(doc, pageWidth, margin, yPosition);
    
    yPosition += 12; // Space after header
    
    // Parse and render markdown content
    const lines = markdownContent.split('\n');
    
    for (const line of lines) {
      // Check for new page
      if (yPosition > pageHeight - margin - 15) {
        doc.addPage();
        addLatexHeader(doc, pageWidth, margin, margin - 5);
        yPosition = margin + 10;
      }
      
      const trimmedLine = line.trim();
      
      // Empty lines - format.tex uses parskip for spacing
      if (trimmedLine === '' || trimmedLine === '---') {
        yPosition += baseLineHeight * 0.5;
        continue;
      }
      
      // Main title (# ) - format.tex: \sectiontitle{} = Large + bold + centered + 6pt vspace
      if (trimmedLine.startsWith('# ')) {
        yPosition += 2.1; // 6pt vspace
        doc.setFontSize(14.4); // LaTeX \Large ≈ 14.4pt
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        const text = trimmedLine.substring(2);
        const textWidth = doc.getTextWidth(text);
        doc.text(text, (pageWidth - textWidth) / 2, yPosition); // Centered
        yPosition += 2.1 + baseLineHeight; // 6pt vspace + line height
      }
      // Section heading (## ) - Regular bold headings
      else if (trimmedLine.startsWith('## ')) {
        yPosition += baseLineHeight * 0.5;
        doc.setFontSize(baseFontSize);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        const text = trimmedLine.substring(3);
        doc.text(text, margin, yPosition);
        yPosition += baseLineHeight * 1.2;
      }
      // Subsection heading (### )
      else if (trimmedLine.startsWith('### ')) {
        yPosition += baseLineHeight * 0.4;
        doc.setFontSize(baseFontSize);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        const text = trimmedLine.substring(4);
        doc.text(text, margin, yPosition);
        yPosition += baseLineHeight * 1.1;
      }
      // List items - format.tex uses enumitem with leftmargin=1.2em
      else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
        doc.setFontSize(baseFontSize);
        doc.setTextColor(0, 0, 0);
        const text = '• ' + trimmedLine.substring(2);
        const indent = 4.2; // 1.2em ≈ 4.2mm
        
        if (text.includes('**')) {
          renderLatexInlineBold(doc, text, margin + indent, yPosition, maxLineWidth - indent, baseFontSize);
          yPosition += baseLineHeight;
        } else {
          const splitText = doc.splitTextToSize(text, maxLineWidth - indent);
          for (const textLine of splitText) {
            if (yPosition > pageHeight - margin - 15) {
              doc.addPage();
              addLatexHeader(doc, pageWidth, margin, margin - 5);
              yPosition = margin + 10;
            }
            doc.setFont('helvetica', 'normal');
            doc.text(textLine, margin + indent, yPosition);
            yPosition += baseLineHeight;
          }
        }
      }
      // Regular paragraph with inline bold
      else if (trimmedLine.includes('**')) {
        doc.setFontSize(baseFontSize);
        doc.setTextColor(0, 0, 0);
        renderLatexInlineBold(doc, trimmedLine, margin, yPosition, maxLineWidth, baseFontSize);
        yPosition += baseLineHeight;
      }
      // Regular paragraph
      else {
        doc.setFontSize(baseFontSize);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0, 0, 0);
        const splitText = doc.splitTextToSize(trimmedLine, maxLineWidth);
        for (const textLine of splitText) {
          if (yPosition > pageHeight - margin - 15) {
            doc.addPage();
            addLatexHeader(doc, pageWidth, margin, margin - 5);
            yPosition = margin + 10;
          }
          doc.text(textLine, margin, yPosition);
          yPosition += baseLineHeight;
        }
      }
    }
    
    // Set document metadata
    doc.setProperties({
      title: filename.replace('.pdf', ''),
      subject: 'Contract Document',
      author: 'eChukti Platform',
      creator: 'eChukti Digital Platform'
    });
    
    // Save the PDF
    doc.save(filename);
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error('Failed to generate PDF. Please try again.');
  }
}

// Add LaTeX-style header matching format.tex
// format.tex: \lhead{\textbf{eChukti} \;|\; Contract Template} \rhead{\thepage}
function addLatexHeader(doc: any, pageWidth: number, margin: number, yPos: number): void {
  const pageNum = doc.getCurrentPageInfo().pageNumber;
  
  // Left header: eChukti | Contract Template
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('eChukti', margin, yPos);
  
  const eChuktiWidth = doc.getTextWidth('eChukti');
  doc.setFont('helvetica', 'normal');
  doc.text(' | Contract Template', margin + eChuktiWidth, yPos);
  
  // Right header: Page number
  doc.setFont('helvetica', 'normal');
  const pageText = String(pageNum);
  const pageTextWidth = doc.getTextWidth(pageText);
  doc.text(pageText, pageWidth - margin - pageTextWidth, yPos);
  
  // Header rule - format.tex: \renewcommand{\headrulewidth}{0.4pt}
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.4 * 0.3527); // 0.4pt to mm
  doc.line(margin, yPos + 1.5, pageWidth - margin, yPos + 1.5);
}

// Helper function to render text with inline bold matching LaTeX \textbf{}
function renderLatexInlineBold(doc: any, text: string, x: number, y: number, _maxWidth: number, fontSize: number): void {
  const parts = text.split('**');
  let currentX = x;
  
  parts.forEach((part, index) => {
    if (part === '') return;
    
    const isBold = index % 2 === 1;
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.text(part, currentX, y);
    currentX += doc.getTextWidth(part);
  });
}
